version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    container_name: django_container
    command: python manage.py runserver 0.0.0.0
