version: '3.8'

services:

  # Redis
  redis:
    image: redis:7.0.6-alpine
    container_name: redis
  
  # Database Postgres

  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data

  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   container_name: postgres_db
  
  #Django application

  backend:
    image: backend
    build: .
    volumes:
      - .:/django_backend
    ports:
      - 8000:8000
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    # depends_on:
    #   - db

  # Celery
  celery:
    restart: always
    build: 
      context: .
    command: celery -A backend worker -l INFO
    volumes:
      - .:/django_backend
    container_name: celery
    depends_on:
      # - db
      - redis
      - backend
